name: Build Joomla Release ZIP

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Extension ZIP
        run: zip -r mod_wmamenumax-${{ github.ref_name }}.zip . -x "*.git*" ".github/*"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: mod_wmamenumax-${{ github.ref_name }}.zip
